import DataTable from "@/components/data-table";
import { Tooltip } from "kitchn";

const LadderTable: React.FC = () => {
	const columns = [
		{
			key: "id",
			header: "#",
			sortable: true,
		},
		{
			key: "name",
			header: "Nom",
			sortable: true,
			filterable: true,
		},
		{
			key: "rank",
			header: "Rang",
			sortable: true,
		},
		{
			key: "lp",
			header: "LPs",
			sortable: true,
		},
		{
			key: "winrate",
			header: "Win%",
			sortable: true,
		},
		{
			key: "top4rate",
			header: "Top 4%",
			sortable: true,
		},
		{
			key: "games",
			header: "Parties",
			sortable: true,
		},
		{
			key: "wins",
			header: "Victoires",
			sortable: true,
		},
		{
			key: "top4",
			header: "Top 4",
			sortable: true,
		},
	];

	return (
		<DataTable
			columns={columns}
			data={[
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
				{
					id: 1,
					name: "vrai jijon#EUW",
					rank: "Challenger",
					lp: 1000,
					winrate: 50,
					top4rate: 50,
					games: 100,
					wins: 50,
					top4: 50,
				},
			]}
			searchPlaceholder="Rechercher un joueur"
		/>
	);
};

export default LadderTable;
